# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(max_length=25)),
                ('cat2', models.CharField(max_length=25)),
                ('brand', models.CharField(default='brand', max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=1, default=5, max_digits=6)),
                ('unit_weight', models.DecimalField(decimal_places=1, default=1, max_digits=6)),
                ('remark', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100, unique=True)),
                ('cn_tracking', models.CharField(max_length=100, null=True, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remark', models.CharField(blank=True, max_length=150, null=True)),
                ('recv_name', models.CharField(max_length=30)),
                ('recv_province', models.CharField(max_length=20)),
                ('recv_city', models.CharField(max_length=20)),
                ('recv_area', models.CharField(max_length=30)),
                ('recv_address', models.CharField(max_length=200)),
                ('recv_zipcode', models.CharField(max_length=30)),
                ('recv_mobile', models.CharField(max_length=30)),
                ('recv_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('charge_rate', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='pallets.Pallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaybillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaybillStatusEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='waybillstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybills.WaybillStatusEntry'),
        ),
        migrations.AddField(
            model_name='waybillstatus',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybills.Waybill'),
        ),
        migrations.AddField(
            model_name='good',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybills.Waybill'),
        ),
    ]
