# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waybills', '0002_auto_20170129_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waybillstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='waybills.WaybillStatusEntry'),
        ),
        migrations.AlterField(
            model_name='waybillstatus',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='waybills.Waybill'),
        ),
    ]
