# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0005_waybillstatus_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='cn_tracking',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
