# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0006_auto_20170131_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='is_self_define',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat1',
            field=models.CharField(max_length=25, verbose_name='\u5927\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat2',
            field=models.CharField(max_length=25, verbose_name='\u5c0f\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(max_length=150, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='good',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=6, verbose_name='\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit_weight',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=6, verbose_name='\u5355\u4f4d\u78c5\u91cd'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='charge_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='cn_tracking',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u56fd\u5185\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5546\u5bb6\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='pallets.Pallet'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='tracking_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u56fd\u9645\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybillstatus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_set', to='waybills.Location'),
        ),
    ]
