# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0008_auto_20170203_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='unit_weight',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3, verbose_name='\u5355\u4f4d\u78c5\u91cd'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='is_self_define',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u81ea\u5b9a\u4e49\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5546\u5bb6\u8ba2\u5355\u53f7'),
        ),
    ]
