# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0009_auto_20170204_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=7, verbose_name='\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='\u5355\u4f4d\u78c5\u91cd'),
        ),
    ]
