# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0010_auto_20170206_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
