# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0014_auto_20170214_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_no', models.CharField(max_length=15, verbose_name='\u7a0e\u53f7')),
                ('name', models.CharField(max_length=50, verbose_name='\u54c1\u540d\u53ca\u89c4\u683c')),
                ('unit', models.CharField(blank=True, max_length=5, null=True, verbose_name='\u5355\u4f4d')),
                ('tax_price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='\u5b8c\u7a0e\u4ef7\u683c')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='\u7a0e\u7387')),
            ],
        ),
    ]
