# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0017_waybill_in_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u6761\u7801'),
        ),
    ]
