# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0018_good_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='is_print_by_manage',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u5728\u51fa\u5355\u754c\u9762\u6253\u5370'),
        ),
    ]
