# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0019_waybill_is_print_by_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='person_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
    ]
