# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0020_waybill_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='third_party_tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u7b2c\u4e09\u53d1\u7269\u6d41\u5355\u53f7'),
        ),
    ]
