# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0021_waybill_third_party_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='hs_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='\u6d77\u5173\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='good',
            name='hs_type_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u6d77\u5173\u7c7b\u522b\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat1',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='\u5927\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='\u5c0f\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit',
            field=models.CharField(blank=True, default='\u4e2a', max_length=10, verbose_name='\u5355\u4f4d'),
        ),
    ]
