# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0022_auto_20170221_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='init_loc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='waybill', to='waybills.Location', verbose_name='\u521d\u59cb\u63a5\u6536\u5730'),
        ),
    ]
