# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0024_auto_20170223_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='QFTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=15, verbose_name='\u5355\u53f7')),
                ('is_used', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7528')),
            ],
        ),
    ]
