# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0026_auto_20170224_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='transaction_no',
            field=models.CharField(editable=False, max_length=32, null=True, unique=True, verbose_name='\u4ea4\u6613\u53f7'),
        ),
    ]
