# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0028_auto_20170225_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transaction_no',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True, verbose_name='\u4ea4\u6613\u53f7'),
        ),
    ]
