# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0032_auto_20170228_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transaction_no',
            field=models.CharField(default=b'<function uuid4 at 0x10e563488>', editable=False, max_length=40, unique=True, verbose_name='\u4ea4\u6613\u53f7'),
        ),
    ]
