# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0035_auto_20170301_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transaction_no',
            field=models.CharField(max_length=40, null=True, verbose_name='\u4ea4\u6613\u53f7'),
        ),
    ]
