# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0036_auto_20170303_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillstatus',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
