# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0037_auto_20170306_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='recv_city',
            field=models.CharField(max_length=15, verbose_name='\u5e02'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='recv_province',
            field=models.CharField(max_length=20, verbose_name='\u7701'),
        ),
    ]
