# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0039_auto_20170309_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='recv_city',
            field=models.CharField(max_length=30, verbose_name='\u5e02'),
        ),
    ]
