# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0040_auto_20170309_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='cn_tracking',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fd\u5185\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='third_party_tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7b2c\u4e09\u65b9\u7269\u6d41\u5355\u53f7'),
        ),
    ]
