# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0041_auto_20170317_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillstatus',
            name='cn_status_json',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
