# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0042_waybillstatus_cn_status_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillstatus',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
