# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0043_waybillstatus_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillstatus',
            name='api_cnt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='api\u67e5\u8be2\u6b21\u6570'),
        ),
    ]
