# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0048_auto_20170404_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='qftracking',
            name='waybill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waybills.Waybill', verbose_name='\u8fd0\u5355'),
        ),
    ]
