# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0050_auto_20170404_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillstatus',
            name='cn_status_json',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
