# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0055_auto_20170605_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
