# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0057_auto_20170904_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='shelf_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='\u8d27\u67b6\u53f7'),
        ),
    ]
