# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0058_waybill_shelf_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='sms_notify_times',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u77ed\u4fe1\u901a\u77e5\u6b21\u6570'),
        ),
    ]
