# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0059_waybill_sms_notify_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qftracking',
            name='tracking_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u5355\u53f7'),
        ),
    ]
