# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0060_auto_20171023_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='yd_info',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='\u97f5\u8fbe\u4fe1\u606f'),
        ),
    ]
