# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0061_waybill_yd_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='yd_info',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='\u97f5\u8fbe\u4fe1\u606f'),
        ),
    ]
