# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0063_cntrackingcreatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cntrackingcreatelog',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u751f\u6210\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
