# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0064_cntrackingcreatelog_create_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='upload_person_id_dt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u8eab\u4efd\u8bc1\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
