# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0065_waybill_upload_person_id_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='tracking_no',
            field=models.CharField(max_length=300, unique=True, verbose_name='\u56fd\u9645\u5355\u53f7'),
        ),
    ]
