# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0067_auto_20180321_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='\u6761\u7801'),
        ),
    ]
