# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20180410_2047'),
        ('waybills', '0068_auto_20180321_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='people',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='addresses.People', verbose_name='people'),
        ),
    ]
