# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0069_waybill_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='shelf_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u8d27\u67b6\u53f7'),
        ),
    ]
