# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0070_auto_20180423_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=9, verbose_name='\u5355\u4ef7'),
        ),
    ]
