# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0071_auto_20180423_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='shelf_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='\u8d27\u67b6\u53f7'),
        ),
    ]
