# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0075_auto_20180502_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionrecord',
            name='waybill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='exception_record', to='waybills.Waybill',
                                       verbose_name='\u8fd0\u5355'),
        ),
    ]
