# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0076_auto_20180502_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='package_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5,
                                      verbose_name='\u6253\u5305\u8d39'),
        ),
    ]
