# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-01 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0078_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='express_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5,
                                      verbose_name='\u8fd0\u8d39'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='tax_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5,
                                      verbose_name='\u7a0e\u8d39'),
        ),
    ]
