# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0080_waybill_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u5b50\u8ba2\u5355\u53f7'),
        ),
        migrations.AddField(
            model_name='good',
            name='shelf_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='\u8d27\u67b6\u53f7'),
        ),
    ]
