# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_order_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_card_backside',
            field=models.ImageField(blank=True, null=True, upload_to='id_card_back/%Y/%m', verbose_name='\u8eab\u4efd\u8bc1\u53cd\u9762\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_card_front/%Y/%m', verbose_name='\u8eab\u4efd\u8bc1\u6b63\u9762\u56fe\u7247'),
        ),
    ]
