# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180410_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_card_backside',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_card_front',
        ),
    ]
