# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7684\u5c0f\u5b57'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7684\u5927\u5b57'),
        ),
    ]
