# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconf', '0002_auto_20180326_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7684\u7b2c\u4e8c\u884c\u5c0f\u5b57'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7684\u7b2c\u4e8c\u884c\u5927\u5b57'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7b2c\u4e00\u884c\u5c0f\u5b57'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6e\u64ad\u56fe\u4e0a\u7684\u7b2c\u4e00\u884c\u5927\u5b57'),
        ),
    ]
