# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconf', '0003_auto_20180326_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
