# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
