# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0002_auto_20170129_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='create_user',
            new_name='user',
        ),
    ]
