# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pallets', '0003_auto_20170129_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u822a\u7a7a\u516c\u53f8\u540d\u79f0')),
                ('code', models.CharField(max_length=10, verbose_name='\u822a\u7a7a\u516c\u53f8\u4ee3\u7801')),
                ('info', models.CharField(max_length=150, verbose_name='\u822a\u7a7a\u516c\u53f8\u4fe1\u606f')),
            ],
        ),
        migrations.CreateModel(
            name='AirWaybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_waybill_no', models.CharField(blank=True, default='', max_length=30, verbose_name='\u822a\u7a7a\u63d0\u5355\u53f7')),
                ('flight_no', models.CharField(blank=True, default='', max_length=10, verbose_name='\u822a\u73ed\u53f7')),
                ('depart_code', models.CharField(max_length=10, verbose_name='\u59cb\u53d1\u6e2f\u4ee3\u7801')),
                ('arrival_code', models.CharField(max_length=10, verbose_name='\u76ee\u7684\u5730\u4ee3\u7801')),
                ('depart_date', models.DateTimeField(verbose_name='\u822a\u73ed\u51fa\u53d1\u65e5\u671f')),
                ('arrival_date', models.DateTimeField(verbose_name='\u822a\u73ed\u5230\u8fbe\u65e5\u671f')),
                ('handling_info', models.CharField(max_length=150, verbose_name='\u5904\u7406\u4fe1\u606f')),
                ('sender_info', models.CharField(max_length=150, verbose_name='\u53d1\u4ef6\u516c\u53f8\u4fe1\u606f')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='air_waybills', to='pallets.Airline', verbose_name='\u822a\u7a7a\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8d27\u4ee3\u540d')),
                ('info', models.CharField(max_length=150, verbose_name='\u8d27\u4ee3\u516c\u53f8\u4fe1\u606f')),
                ('iata', models.CharField(max_length=10, verbose_name='\u8d27\u4ee3IATA\u4ee3\u7801')),
                ('account_no', models.CharField(max_length=10, verbose_name='\u8d27\u4ee3\u7ed3\u7b97\u8d26\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6536\u4ef6\u516c\u53f8\u540d')),
                ('info', models.CharField(max_length=150, verbose_name='\u6536\u4ef6\u516c\u53f8\u4fe1\u606f')),
            ],
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='air_waybills', to='pallets.Carrier', verbose_name='\u8d27\u4ee3\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='air_waybills', to='pallets.Receiver', verbose_name='\u6536\u4ef6\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='air_waybills', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='air_waybill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='pallets.AirWaybill'),
        ),
    ]
