# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0004_auto_20170214_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='batch_no',
            new_name='pallet_no',
        ),
    ]
