# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0009_auto_20170303_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='is_send_out',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u51fa\u5e93'),
        ),
    ]
