# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0010_pallet_is_send_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='is_send_out',
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='is_send_out',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u51fa\u5e93'),
        ),
    ]
