# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0012_auto_20170317_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='air_waybills', to='pallets.Channel', verbose_name='\u6e20\u9053'),
        ),
    ]
