# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0013_airwaybill_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='status',
            field=models.IntegerField(default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
