# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0014_airwaybill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='loc',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5730\u70b9'),
        ),
    ]
