# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0015_channel_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
