# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pallets', '0016_pallet_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='pallets', to='pallets.Channel'),
        ),
    ]
