# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pallets', '0017_pallet_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5,
                                      verbose_name='\u9996\u78c5'),
        ),
        migrations.AddField(
            model_name='channel',
            name='next_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5,
                                      verbose_name='\u7eed\u78c5'),
        ),
        migrations.AddField(
            model_name='channel',
            name='tax',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f81\u7a0e'),
        ),
    ]
