# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='good',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='waybills.Waybill'),
        ),
    ]
