# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0011_location_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='init_loc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='waybills.Location', verbose_name='\u521d\u59cb\u63a5\u6536\u5730'),
        ),
    ]
