# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0012_waybill_init_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_us_node',
            field=models.BooleanField(default=False),
        ),
    ]
