# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0013_location_is_us_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, verbose_name='\u53d1\u7968\u53f7\u7801')),
                ('depart_loc', models.CharField(max_length=20, verbose_name='\u8d77\u8fd0\u5730')),
                ('arrival_loc', models.CharField(max_length=20, verbose_name='\u76ee\u7684\u5730')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='waybills.Waybill', verbose_name='\u8fd0\u5355')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u82f1\u6587\u540d'),
        ),
        migrations.AddField(
            model_name='good',
            name='spec',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u89c4\u683c\u4fe1\u53f7'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u5355\u4f4d'),
        ),
    ]
