# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0015_taxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxitem',
            name='is_parrent',
            field=models.BooleanField(default=False, verbose_name='\u5927\u7c7b\u76ee'),
        ),
    ]
