# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0016_taxitem_is_parrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='in_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='\u5bfc\u5165\u6279\u6b21'),
        ),
    ]
