# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0023_auto_20170223_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='init_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybill', to='waybills.Location', verbose_name='\u521d\u59cb\u63a5\u6536\u5730'),
        ),
    ]
