# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0025_qftracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='in_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='\u5efa\u5355\u6279\u6b21'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='third_party_tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u7b2c\u4e09\u65b9\u7269\u6d41\u5355\u53f7'),
        ),
    ]
