# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0046_auto_20170321_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='waybills.WaybillStatusEntry', verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='waybillstatus',
            name='cn_status_json',
            field=models.CharField(blank=True, default=None, max_length=6000, null=True),
        ),
    ]
