# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0047_auto_20170403_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qftracking',
            name='tracking_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='\u5355\u53f7'),
        ),
    ]
