# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0052_auto_20170506_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='cn_tracking',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='\u56fd\u5185\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='src_loc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='waybills.SrcLoc', verbose_name='\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='third_party_tracking_no',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='\u7b2c\u4e09\u65b9\u7269\u6d41\u5355\u53f7'),
        ),
    ]
