# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0014_airwaybill_status'),
        ('waybills', '0053_auto_20170507_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='pallets.Channel'),
        ),
    ]
