# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0054_waybill_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillstatusentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='pallets.Channel', verbose_name='\u6e20\u9053'),
        ),
    ]
