# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0015_channel_loc'),
        ('waybills', '0062_auto_20171025_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnTrackingCreateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_tracking', models.CharField(max_length=100, verbose_name='\u56fd\u9645\u5355\u53f7')),
                ('cn_tracking', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fd\u5185\u5355\u53f7')),
                ('msg', models.CharField(blank=True, max_length=200, verbose_name='\u7ed3\u679c\u4fe1\u606f')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='\u72b6\u6001\u7801')),
                ('other', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5176\u4ed6\u4fe1\u606f')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cn_tracking_create_logs', to='pallets.Channel', verbose_name='\u6e20\u9053')),
            ],
        ),
    ]
