# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0074_exceptionrecord_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionrecord',
            name='waybill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='exception_record', to='waybills.Waybill', unique=True,
                                    verbose_name='\u8fd0\u5355'),
        ),
    ]
