# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0077_waybill_package_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='\u6c47\u7387')),
                ('create_dt', models.DateField(auto_now_add=True, verbose_name='\u6c47\u7387\u65e5\u671f')),
            ],
        ),
    ]
