# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waybills', '0079_auto_20180601_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='is_billed',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u51fa\u8d26\u5355'),
        ),
    ]
