# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0011_location_short_name'),
        ('accounts', '0010_auto_20170207_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waybills.Location', verbose_name='\u6700\u8fd1\u7684\u96c6\u8fd0\u4e2d\u5fc3'),
        ),
    ]
