# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_dt',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='\u5220\u9664'),
        ),
    ]
