# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180401_1442'),
        ('blog', '0004_auto_20180410_2044'),
    ]

    operations = [
    ]
