# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.People'),
        ),
    ]
