# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('ems_mark1', models.CharField(max_length=30)),
            ],
        ),
    ]
