# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0008_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='air_waybill_no',
            field=models.CharField(blank=True, default='', max_length=30, unique=True, verbose_name='\u822a\u7a7a\u63d0\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='pallet_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
