# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170204_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybills.Location', verbose_name='\u5de5\u4f5c\u4f4d\u7f6e'),
        ),
        migrations.DeleteModel(
            name='Loc',
        ),
    ]
